"""final_verify

Revision ID: 18c83814ef57
Revises: 
Create Date: 2026-02-03 17:03:06.643839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18c83814ef57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ifcontrls', 'uuid',
               existing_type=mysql.VARCHAR(length=32),
               comment='Primary Key',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'gm_id',
               existing_type=mysql.TEXT(),
               comment='業務ID(2)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'storeId',
               existing_type=mysql.VARCHAR(length=6),
               comment='門市Code(6)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'short_name',
               existing_type=mysql.TEXT(),
               comment='門市名稱（略式）(6)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'corp_name',
               existing_type=mysql.TEXT(),
               comment='統一發票公司名１(24)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'corp_name_2',
               existing_type=mysql.TEXT(),
               comment='統一發票公司名２(24)',
               existing_nullable=True)
    op.alter_column('ifcontrls', 'corp_id',
               existing_type=mysql.TEXT(),
               comment='統一發票公司代號(8)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'dis_flg',
               existing_type=mysql.TEXT(),
               comment='折扣Key區分(1)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'dis_type',
               existing_type=mysql.TEXT(),
               comment='折扣區分(1)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'discount',
               existing_type=mysql.TEXT(),
               comment='折扣率/金額(4)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'dis_fra_flg',
               existing_type=mysql.TEXT(),
               comment='折扣端數處理區分(1)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'ex_dis_flg',
               existing_type=mysql.TEXT(),
               comment='免税商品折扣區分(1)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'long_name',
               existing_type=mysql.TEXT(),
               comment='Long Name',
               existing_nullable=True)
    op.alter_column('ifcontrls', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Soft delete timestamp',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ifcontrls', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('ifcontrls', 'long_name',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Long Name',
               existing_nullable=True)
    op.alter_column('ifcontrls', 'ex_dis_flg',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='免税商品折扣區分(1)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'dis_fra_flg',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='折扣端數處理區分(1)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'discount',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='折扣率/金額(4)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'dis_type',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='折扣區分(1)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'dis_flg',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='折扣Key區分(1)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'corp_id',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='統一發票公司代號(8)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'corp_name_2',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='統一發票公司名２(24)',
               existing_nullable=True)
    op.alter_column('ifcontrls', 'corp_name',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='統一發票公司名１(24)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'short_name',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='門市名稱（略式）(6)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'storeId',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='門市Code(6)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'gm_id',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='業務ID(2)',
               existing_nullable=False)
    op.alter_column('ifcontrls', 'uuid',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='Primary Key',
               existing_nullable=False)
    # ### end Alembic commands ###
