"""verify_final_cumulative

Revision ID: 85779e9f4e86
Revises: 18c83814ef57
Create Date: 2026-02-03 17:28:03.395564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85779e9f4e86'
down_revision: Union[str, Sequence[str], None] = '18c83814ef57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_payuni_credithash',
    sa.Column('gid', sa.String(length=255), nullable=False),
    sa.Column('credithash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('checkout_sms_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('op_gid', sa.String(length=50), nullable=True, comment='GID'),
    sa.Column('session_start', sa.String(length=255), nullable=False, comment='session_start'),
    sa.Column('order_id', sa.String(length=28), nullable=True, comment='訂單編號'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='調解類型'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkout_sms_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('op_gid', sa.String(length=50), nullable=True, comment='GID'),
    sa.Column('session_start', sa.String(length=255), nullable=False, comment='session_start'),
    sa.Column('order_id', sa.String(length=28), nullable=True, comment='訂單編號'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='調解類型'),
    sa.Column('plu_code', sa.Text(), nullable=False, comment='PLU Code(8||13)'),
    sa.Column('count', sa.Integer(), nullable=False, comment='購買數量'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='商品名稱'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('i_c_p_settle_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('countSum', sa.Integer(), nullable=False),
    sa.Column('moneySum', sa.Integer(), nullable=False),
    sa.Column('realAmount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('originalContent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('i_c_p_settle_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('discount_point', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('transaction_results_information', sa.Text(), nullable=True),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxySales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('icp_side_comparison_results', sa.String(length=1), nullable=False),
    sa.Column('icp_side_comparison_result_code', sa.String(length=5), nullable=False),
    sa.Column('icp_side_comparison_result_description', sa.Text(), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p_a_y_u_ni_settle_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('countSum', sa.Integer(), nullable=False),
    sa.Column('moneySum', sa.Integer(), nullable=False),
    sa.Column('realAmount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('originalContent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p_a_y_u_ni_settle_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('bank_code', sa.String(length=3), nullable=True),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('discount_point', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('transaction_results_information', sa.Text(), nullable=True),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxySales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('bank_side_comparison_results', sa.String(length=1), nullable=False),
    sa.Column('bank_side_comparison_result_code', sa.String(length=5), nullable=False),
    sa.Column('bank_side_comparison_result_description', sa.Text(), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('send_to_s_c_host_daily_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('send_to_s_c_host_data',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('storeId', sa.String(length=6), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_cancel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ifbookms', sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'))
    op.add_column('ifmntexts', sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'))
    op.add_column('ifnotdis', sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'))
    op.add_column('ifpluexts', sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'))
    op.add_column('iftouchps', sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iftouchps', 'storeId')
    op.drop_column('ifpluexts', 'storeId')
    op.drop_column('ifnotdis', 'storeId')
    op.drop_column('ifmntexts', 'storeId')
    op.drop_column('ifbookms', 'storeId')
    op.drop_table('send_to_s_c_host_data')
    op.drop_table('send_to_s_c_host_daily_data')
    op.drop_table('p_a_y_u_ni_settle_detail_files')
    op.drop_table('p_a_y_u_ni_settle_consolidate_files')
    op.drop_table('i_c_p_settle_detail_files')
    op.drop_table('i_c_p_settle_consolidate_files')
    op.drop_table('checkout_sms_detail_files')
    op.drop_table('checkout_sms_consolidate_files')
    op.drop_table('checkout_payuni_credithash')
    # ### end Alembic commands ###
