"""initial_migration_users_and_orders

Revision ID: ac9caa929345
Revises: 
Create Date: 2026-02-03 15:43:22.138227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9caa929345'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('rno', sa.String(length=6), nullable=False),
    sa.Column('storeId', sa.String(length=6), nullable=False),
    sa.Column('before_discount_tx_price', sa.Integer(), nullable=False),
    sa.Column('tx_discount_amount', sa.Integer(), nullable=False),
    sa.Column('after_discount_tx_price', sa.Integer(), nullable=False),
    sa.Column('before_discount_ex_price', sa.Integer(), nullable=False),
    sa.Column('ex_discount_amount', sa.Integer(), nullable=False),
    sa.Column('after_discount_ex_price', sa.Integer(), nullable=False),
    sa.Column('payable_amount', sa.Integer(), nullable=False),
    sa.Column('amount_actually_paid', sa.Integer(), nullable=False),
    sa.Column('pay_type', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_storeId'), 'orders', ['storeId'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('owner_name', sa.String(length=10), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('logintimes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_account'), 'users', ['account'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_account'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_orders_storeId'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
