"""verify_models_alignment

Revision ID: e76254c9984e
Revises: 85779e9f4e86
Create Date: 2026-02-04 01:17:00.690795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e76254c9984e'
down_revision: Union[str, Sequence[str], None] = '85779e9f4e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b_m_s_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False, comment='檔頭標籤'),
    sa.Column('time', sa.String(length=14), nullable=False, comment='檔案時間'),
    sa.Column('countSum', sa.Integer(), nullable=False, comment='總筆數'),
    sa.Column('moneySum', sa.Integer(), nullable=False, comment='總金額'),
    sa.Column('handlingFeeSum', sa.Integer(), nullable=False, comment='手續費總金額'),
    sa.Column('originalContent', sa.Text(), nullable=False, comment='原始內容'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b_m_s_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('consumer_authentication_code', sa.String(length=25), nullable=True),
    sa.Column('exchange_rate', sa.Integer(), nullable=False),
    sa.Column('transfer_amount', sa.Integer(), nullable=False),
    sa.Column('transaction_results_information', sa.Text(), nullable=True),
    sa.Column('reason_for_refund', sa.Text(), nullable=True),
    sa.Column('handling_fee_amount', sa.Float(), nullable=False),
    sa.Column('general_handling_fee', sa.Float(), nullable=False),
    sa.Column('handling_fee_for_collection_amount', sa.Float(), nullable=False),
    sa.Column('proxy_sales_amount_handling_fee_amount', sa.Float(), nullable=False),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxySales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('transaction_notes', sa.String(length=1), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banks',
    sa.Column('bank_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_institution_code', sa.String(length=10), nullable=False, comment='支付機構代碼'),
    sa.Column('bank_code', sa.String(length=7), nullable=False, comment='銀行代碼'),
    sa.Column('bank_name', sa.String(length=50), nullable=False, comment='銀行名稱'),
    sa.Column('bank_short_name', sa.String(length=20), nullable=False, comment='銀行簡稱'),
    sa.Column('bank_type', sa.String(length=10), nullable=False, comment='是否為併機行 (Y:併機行/N:非併機行)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='狀態 (1:啟用/0:停用)'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='生效日期'),
    sa.Column('expire_date', sa.Date(), nullable=True, comment='失效日期'),
    sa.Column('create_user', sa.String(length=20), nullable=False, comment='建立人員'),
    sa.Column('update_user', sa.String(length=20), nullable=True, comment='更新人員'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bank_id'),
    sa.UniqueConstraint('bank_code')
    )
    op.create_table('c_t_b_c_diff_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False, comment='檔頭標籤'),
    sa.Column('time', sa.String(length=14), nullable=False, comment='檔案時間'),
    sa.Column('countSum', sa.Integer(), nullable=False, comment='總筆數'),
    sa.Column('moneySum', sa.Integer(), nullable=False, comment='總金額'),
    sa.Column('bank_code', sa.String(length=3), nullable=False, comment='銀行代碼'),
    sa.Column('originalContent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('c_t_b_c_diff_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('diff_type', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('bank_code', sa.String(length=3), nullable=True),
    sa.Column('order_id', sa.String(length=28), nullable=False, comment='特店交易編號'),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('discount_point', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('consumer_authentication_code', sa.String(length=25), nullable=True),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxy_sales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('merchant_id', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('c_t_b_c_settle_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False, comment='檔頭標籤'),
    sa.Column('time', sa.String(length=14), nullable=False, comment='檔案時間'),
    sa.Column('countSum', sa.Integer(), nullable=False, comment='總筆數'),
    sa.Column('moneySum', sa.Integer(), nullable=False, comment='總金額'),
    sa.Column('realAmount', sa.Integer(), nullable=False, comment='撥款金額'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='撥款區間-起'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='撥款區間-訖'),
    sa.Column('bank_code', sa.String(length=3), nullable=False, comment='銀行代碼'),
    sa.Column('originalContent', sa.Text(), nullable=False, comment='彙整檔的原始內容'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('c_t_b_c_settle_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('bank_code', sa.String(length=3), nullable=True),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('discount_point', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('transaction_results_information', sa.Text(), nullable=True),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxy_sales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('bank_side_comparison_results', sa.String(length=1), nullable=False),
    sa.Column('bank_side_comparison_result_code', sa.String(length=5), nullable=False),
    sa.Column('bank_side_comparison_result_description', sa.Text(), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cathay_diff_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('countSum', sa.Integer(), nullable=False),
    sa.Column('moneySum', sa.Integer(), nullable=False),
    sa.Column('originalContent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cathay_diff_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('diff_type', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('bank_code', sa.String(length=3), nullable=True),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('discount_point', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('consumer_authentication_code', sa.String(length=25), nullable=True),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxySales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cathay_settle_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('countSum', sa.Integer(), nullable=False),
    sa.Column('moneySum', sa.Integer(), nullable=False),
    sa.Column('realAmount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('originalContent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cathay_settle_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('bank_code', sa.String(length=3), nullable=True),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('discount_point', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('transaction_results_information', sa.Text(), nullable=True),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxySales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('bank_side_comparison_results', sa.String(length=1), nullable=False),
    sa.Column('bank_side_comparison_result_code', sa.String(length=5), nullable=False),
    sa.Column('bank_side_comparison_result_description', sa.Text(), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failed_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('connection', sa.Text(), nullable=False),
    sa.Column('queue', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('exception', sa.Text(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('gps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('check_gps', sa.Boolean(), nullable=False, comment='是否檢查 GPS 定位'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('i_c_p_diff_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('countSum', sa.Integer(), nullable=False),
    sa.Column('moneySum', sa.Integer(), nullable=False),
    sa.Column('originalContent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('i_c_p_diff_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('diff_type', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('discount_point', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('consumer_authentication_code', sa.String(length=25), nullable=True),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxySales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ifbookms',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('gmid', sa.Text(), nullable=False, comment='業務ID(2)'),
    sa.Column('plu_code', sa.Text(), nullable=False, comment='PLU Code(13)'),
    sa.Column('s_plu_code', sa.Text(), nullable=False, comment='第２段 Code(13)'),
    sa.Column('name', sa.Text(), nullable=False, comment='PLU名稱(30)'),
    sa.Column('price', sa.Text(), nullable=False, comment='單價(9)'),
    sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('ifmntexts',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('gmid', sa.Text(), nullable=False, comment='業務ID(5U,2)'),
    sa.Column('mkbn', sa.Text(), nullable=False, comment='Maintenance區分(1)'),
    sa.Column('plu_code', sa.Text(), nullable=False, comment='PLU Code(8||13)'),
    sa.Column('inner_code', sa.Text(), nullable=False, comment='INNER Code(6)'),
    sa.Column('name', sa.Text(), nullable=False, comment='商品名稱(30)'),
    sa.Column('tax_flg', sa.Text(), nullable=False, comment='稅別(2)'),
    sa.Column('type_1', sa.Text(), nullable=False, comment='商品區分１(2)'),
    sa.Column('price', sa.Text(), nullable=False, comment='門市零售價(9)'),
    sa.Column('pma_code', sa.Text(), nullable=False, comment='PMACode(2)'),
    sa.Column('md_code', sa.Text(), nullable=False, comment='中分類Code(2)'),
    sa.Column('sd_code', sa.Text(), nullable=False, comment='小分類Code(2)'),
    sa.Column('m_code', sa.Text(), nullable=False, comment='MatrixCode(2)'),
    sa.Column('sb_date_time', sa.Text(), nullable=False, comment='暫停銷售開始日時(12)'),
    sa.Column('se_date_time', sa.Text(), nullable=False, comment='暫停銷售停止日時(12)'),
    sa.Column('intl_code', sa.Text(), nullable=False, comment='單品條碼種類(1)'),
    sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('ifnotdis',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('gmid', sa.Text(), nullable=False, comment='業務ID(2)'),
    sa.Column('start_date', sa.Text(), nullable=False, comment='開始日(8)'),
    sa.Column('end_date', sa.Text(), nullable=False, comment='開始日(8)'),
    sa.Column('unit_type', sa.Text(), nullable=False, comment='不可折扣類型(1)'),
    sa.Column('pma_code', sa.Text(), nullable=False, comment='PMA(2)'),
    sa.Column('m_code', sa.Text(), nullable=False, comment='中分類(2)'),
    sa.Column('item_no', sa.Text(), nullable=False, comment='單品(6)'),
    sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('ifpluexts',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('gmid', sa.Text(), nullable=False, comment='業務ID(5T,2)'),
    sa.Column('mkbn', sa.Text(), nullable=False, comment='Maintenance區分(1)'),
    sa.Column('plu_code', sa.Text(), nullable=False, comment='PLU Code(8||13)'),
    sa.Column('inner_code', sa.Text(), nullable=False, comment='INNER Code(6)'),
    sa.Column('name', sa.Text(), nullable=False, comment='商品名稱(30)'),
    sa.Column('tax_flg', sa.Text(), nullable=False, comment='稅別(2)'),
    sa.Column('type_1', sa.Text(), nullable=False, comment='商品區分１(2)'),
    sa.Column('price', sa.Text(), nullable=False, comment='門市零售價(9)'),
    sa.Column('pma_code', sa.Text(), nullable=False, comment='PMACode(2)'),
    sa.Column('md_code', sa.Text(), nullable=False, comment='中分類Code(2)'),
    sa.Column('sd_code', sa.Text(), nullable=False, comment='小分類Code(2)'),
    sa.Column('m_code', sa.Text(), nullable=False, comment='MatrixCode(2)'),
    sa.Column('sb_date_time', sa.Text(), nullable=False, comment='暫停銷售開始日時(12)'),
    sa.Column('se_date_time', sa.Text(), nullable=False, comment='暫停銷售停止日時(12)'),
    sa.Column('intl_code', sa.Text(), nullable=False, comment='單品條碼種類(1)'),
    sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('iftouchps',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('gmid', sa.Text(), nullable=False, comment='業務ID(06,2)'),
    sa.Column('touch_id', sa.Text(), nullable=False, comment='TouchＮｏ(2)'),
    sa.Column('display_no', sa.Text(), nullable=False, comment='表示No(2)'),
    sa.Column('pflg', sa.Text(), nullable=False, comment='Panel區分(1)'),
    sa.Column('plu_code', sa.Text(), nullable=False, comment='PLUCode(13)'),
    sa.Column('disp_name_1', sa.Text(), nullable=False, comment='表示名稱第一段(10)'),
    sa.Column('disp_name_2', sa.Text(), nullable=False, comment='表示名稱第二段(10)'),
    sa.Column('storeId', sa.String(length=6), nullable=True, comment='門市Code(6)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('order_short_keys',
    sa.Column('short_key', sa.String(length=6), nullable=False),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('short_key')
    )
    op.create_table('p_a_y_u_ni_diff_consolidate_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('time', sa.String(length=14), nullable=False),
    sa.Column('countSum', sa.Integer(), nullable=False),
    sa.Column('moneySum', sa.Integer(), nullable=False),
    sa.Column('originalContent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p_a_y_u_ni_diff_detail_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=1), nullable=False),
    sa.Column('diff_type', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('bank_code', sa.String(length=3), nullable=True),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('o2oId', sa.String(length=64), nullable=True),
    sa.Column('payment_institution_transaction_number', sa.String(length=64), nullable=True),
    sa.Column('transaction_time', sa.String(length=14), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('discount_point', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('terminal_code', sa.String(length=3), nullable=False),
    sa.Column('consumer_authentication_code', sa.String(length=25), nullable=True),
    sa.Column('general_amount', sa.Integer(), nullable=False),
    sa.Column('collection_amount', sa.Integer(), nullable=False),
    sa.Column('proxySales_amount', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=6), nullable=False),
    sa.Column('pos_id', sa.String(length=2), nullable=False),
    sa.Column('cash_register_transaction_serial_number', sa.String(length=6), nullable=False),
    sa.Column('bonus_activity_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storeId', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('websockets_statistics_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('peak_connection_count', sa.Integer(), nullable=False),
    sa.Column('websocket_message_count', sa.Integer(), nullable=False),
    sa.Column('api_message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_has_permissions',
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('model_type', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'model_type', 'model_id')
    )
    op.create_table('model_has_roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('model_type', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'model_type', 'model_id')
    )
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=28), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False, comment='0 => 尚未付款; 1 => 付款完成; 2 => 已退貨'),
    sa.Column('content', sa.Text(), nullable=True, comment='附屬訊息'),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='狀態產生時間'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_statuses_order_id'), 'order_statuses', ['order_id'], unique=False)
    op.create_table('role_has_permissions',
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'role_id')
    )
    op.alter_column('ifcontrls', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('ifcontrls', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.add_column('order_details', sa.Column('no_discount_type', sa.Integer(), nullable=False, comment='No Discount Type'))
    op.add_column('order_details', sa.Column('cherish_flg', mysql.TINYINT(), nullable=False, comment='珍食標記 (0: 否, 1: 是)'))
    op.alter_column('order_details', 'id',
               existing_type=mysql.VARCHAR(length=28),
               comment='訂單編號',
               existing_nullable=False)
    op.alter_column('order_details', 'plu_code',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               comment='商品PluCode',
               existing_nullable=False)
    op.alter_column('order_details', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               comment='商品名稱',
               existing_nullable=False)
    op.alter_column('order_details', 'price',
               existing_type=mysql.INTEGER(),
               comment='商品價錢',
               existing_nullable=False)
    op.alter_column('order_details', 'count',
               existing_type=mysql.INTEGER(),
               comment='商品購買數量',
               existing_nullable=False)
    op.alter_column('order_details', 'tax_flg',
               existing_type=mysql.VARCHAR(length=2),
               type_=mysql.TINYINT(),
               comment='商品稅別(00 => 應稅(已含稅)、 01 => 免稅)',
               existing_nullable=False)
    op.alter_column('order_details', 'is_discount',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否要打折',
               existing_nullable=False)
    op.alter_column('order_details', 'discount_type',
               existing_type=mysql.INTEGER(),
               comment='打折類型(0 => 百分比、1 => 金額)',
               existing_nullable=True)
    op.alter_column('order_details', 'discount',
               existing_type=mysql.INTEGER(),
               comment='折扣率或金額',
               existing_nullable=True)
    op.alter_column('order_details', 'discount_fra_type',
               existing_type=mysql.INTEGER(),
               comment='小數點處理方式(0 => 無條件進位\u30001 => 四捨五入\u30002 => 無條件捨去)',
               existing_nullable=True)
    op.alter_column('order_details', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_details', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_details', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Soft delete timestamp',
               existing_nullable=True)
    op.add_column('orders', sa.Column('phone', sa.String(length=255), nullable=True, comment='Phone (Encrypted)'))
    op.add_column('orders', sa.Column('op_gid', sa.String(length=50), nullable=True, comment='Open Point Member GID'))
    op.add_column('orders', sa.Column('no_discount_total_price', sa.Integer(), nullable=False, comment='No Discount Total Price'))
    op.add_column('orders', sa.Column('tx_no_discount_price', mysql.INTEGER(unsigned=True), nullable=False, comment='TX No Discount Price'))
    op.add_column('orders', sa.Column('ex_no_discount_price', mysql.INTEGER(unsigned=True), nullable=False, comment='EX No Discount Price'))
    op.add_column('orders', sa.Column('ifood_discount_price', mysql.INTEGER(unsigned=True), nullable=False, comment='iFood 折扣金額'))
    op.add_column('orders', sa.Column('SDK_content', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('TRI_Api_Request', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('ITRI_Order_No', sa.String(length=50), nullable=True, comment='中研院傳進來的訂單編號'))
    op.add_column('orders', sa.Column('ITRI_rno', sa.String(length=50), nullable=True, comment='中研院傳進來的rno'))
    op.alter_column('orders', 'id',
               existing_type=mysql.VARCHAR(length=28),
               comment='訂單編號',
               existing_nullable=False)
    op.alter_column('orders', 'rno',
               existing_type=mysql.VARCHAR(length=6),
               comment='流水號 000001~999999',
               existing_nullable=False)
    op.alter_column('orders', 'storeId',
               existing_type=mysql.VARCHAR(length=6),
               comment='商店編號',
               existing_nullable=False)
    op.alter_column('orders', 'before_discount_tx_price',
               existing_type=mysql.INTEGER(),
               comment='應稅商品折扣前價錢',
               existing_nullable=False)
    op.alter_column('orders', 'tx_discount_amount',
               existing_type=mysql.INTEGER(),
               comment='應稅商品折扣額',
               existing_nullable=False)
    op.alter_column('orders', 'after_discount_tx_price',
               existing_type=mysql.INTEGER(),
               comment='應稅商品折扣後額',
               existing_nullable=False)
    op.alter_column('orders', 'before_discount_ex_price',
               existing_type=mysql.INTEGER(),
               comment='免稅商品折扣前價錢',
               existing_nullable=False)
    op.alter_column('orders', 'ex_discount_amount',
               existing_type=mysql.INTEGER(),
               comment='免稅商品折扣額',
               existing_nullable=False)
    op.alter_column('orders', 'after_discount_ex_price',
               existing_type=mysql.INTEGER(),
               comment='免稅商品折扣後額',
               existing_nullable=False)
    op.alter_column('orders', 'payable_amount',
               existing_type=mysql.INTEGER(),
               comment='訂單應付金額',
               existing_nullable=False)
    op.alter_column('orders', 'amount_actually_paid',
               existing_type=mysql.INTEGER(),
               comment='訂單實付金額',
               existing_nullable=False)
    op.alter_column('orders', 'pay_type',
               existing_type=mysql.VARCHAR(length=15),
               comment='付款方式',
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('orders', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('orders', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Soft delete timestamp',
               existing_nullable=True)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.add_column('permissions', sa.Column('pid', sa.String(length=36), nullable=True))
    op.alter_column('permissions', 'subject',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('permissions', 'sort',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('permissions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('uq_permission_name_guard'), table_name='permissions')
    op.add_column('roles', sa.Column('storeId', sa.Text(), nullable=True))
    op.alter_column('roles', 'subject',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('uq_role_name_guard'), table_name='roles')
    op.add_column('stores', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('stores', sa.Column('QRcode', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('gps_limitLat', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('gps_limitLng', sa.Float(), nullable=True))
    op.alter_column('stores', 'type',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('stores', 'color',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('stores', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('stores', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_stores_storeId'), table_name='stores')
    op.create_index(op.f('ix_stores_storeId'), 'stores', ['storeId'], unique=True)
    op.drop_column('stores', 'qr_code')
    op.drop_column('stores', 'gps')
    op.alter_column('users', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               comment='Primary Key',
               existing_nullable=False)
    op.alter_column('users', 'account',
               existing_type=mysql.VARCHAR(length=20),
               comment='User Account',
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=255),
               comment='Encrypted Password',
               existing_nullable=False)
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(length=20),
               comment='Department',
               existing_nullable=True)
    op.alter_column('users', 'owner_name',
               existing_type=mysql.VARCHAR(length=10),
               comment='Owner Name',
               existing_nullable=True)
    op.alter_column('users', 'expiry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               comment='Expiry Date',
               existing_nullable=True)
    op.alter_column('users', 'disabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Is Disabled',
               existing_nullable=False)
    op.alter_column('users', 'logintimes',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='Login Times')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'logintimes',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Login Times')
    op.alter_column('users', 'disabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Is Disabled',
               existing_nullable=False)
    op.alter_column('users', 'expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               comment=None,
               existing_comment='Expiry Date',
               existing_nullable=True)
    op.alter_column('users', 'owner_name',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='Owner Name',
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Department',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=60),
               comment=None,
               existing_comment='Encrypted Password',
               existing_nullable=False)
    op.alter_column('users', 'account',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='User Account',
               existing_nullable=False)
    op.alter_column('users', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='Primary Key',
               existing_nullable=False)
    op.add_column('stores', sa.Column('gps', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('stores', sa.Column('qr_code', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_stores_storeId'), table_name='stores')
    op.create_index(op.f('ix_stores_storeId'), 'stores', ['storeId'], unique=False)
    op.alter_column('stores', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('stores', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('stores', 'color',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('stores', 'type',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               nullable=False)
    op.drop_column('stores', 'gps_limitLng')
    op.drop_column('stores', 'gps_limitLat')
    op.drop_column('stores', 'QRcode')
    op.drop_column('stores', 'id')
    op.create_index(op.f('uq_role_name_guard'), 'roles', ['name', 'guard_name'], unique=True)
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('roles', 'subject',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('roles', 'storeId')
    op.create_index(op.f('uq_permission_name_guard'), 'permissions', ['name', 'guard_name'], unique=True)
    op.alter_column('permissions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('permissions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('permissions', 'sort',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('permissions', 'subject',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('permissions', 'pid')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.alter_column('orders', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('orders', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('orders', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('orders', 'pay_type',
               existing_type=mysql.VARCHAR(length=15),
               comment=None,
               existing_comment='付款方式',
               existing_nullable=False)
    op.alter_column('orders', 'amount_actually_paid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='訂單實付金額',
               existing_nullable=False)
    op.alter_column('orders', 'payable_amount',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='訂單應付金額',
               existing_nullable=False)
    op.alter_column('orders', 'after_discount_ex_price',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='免稅商品折扣後額',
               existing_nullable=False)
    op.alter_column('orders', 'ex_discount_amount',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='免稅商品折扣額',
               existing_nullable=False)
    op.alter_column('orders', 'before_discount_ex_price',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='免稅商品折扣前價錢',
               existing_nullable=False)
    op.alter_column('orders', 'after_discount_tx_price',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='應稅商品折扣後額',
               existing_nullable=False)
    op.alter_column('orders', 'tx_discount_amount',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='應稅商品折扣額',
               existing_nullable=False)
    op.alter_column('orders', 'before_discount_tx_price',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='應稅商品折扣前價錢',
               existing_nullable=False)
    op.alter_column('orders', 'storeId',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='商店編號',
               existing_nullable=False)
    op.alter_column('orders', 'rno',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='流水號 000001~999999',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=mysql.VARCHAR(length=28),
               comment=None,
               existing_comment='訂單編號',
               existing_nullable=False)
    op.drop_column('orders', 'ITRI_rno')
    op.drop_column('orders', 'ITRI_Order_No')
    op.drop_column('orders', 'TRI_Api_Request')
    op.drop_column('orders', 'SDK_content')
    op.drop_column('orders', 'ifood_discount_price')
    op.drop_column('orders', 'ex_no_discount_price')
    op.drop_column('orders', 'tx_no_discount_price')
    op.drop_column('orders', 'no_discount_total_price')
    op.drop_column('orders', 'op_gid')
    op.drop_column('orders', 'phone')
    op.alter_column('order_details', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('order_details', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_details', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_details', 'discount_fra_type',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='小數點處理方式(0 => 無條件進位\u30001 => 四捨五入\u30002 => 無條件捨去)',
               existing_nullable=True)
    op.alter_column('order_details', 'discount',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='折扣率或金額',
               existing_nullable=True)
    op.alter_column('order_details', 'discount_type',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='打折類型(0 => 百分比、1 => 金額)',
               existing_nullable=True)
    op.alter_column('order_details', 'is_discount',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否要打折',
               existing_nullable=False)
    op.alter_column('order_details', 'tax_flg',
               existing_type=mysql.TINYINT(),
               type_=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='商品稅別(00 => 應稅(已含稅)、 01 => 免稅)',
               existing_nullable=False)
    op.alter_column('order_details', 'count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='商品購買數量',
               existing_nullable=False)
    op.alter_column('order_details', 'price',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='商品價錢',
               existing_nullable=False)
    op.alter_column('order_details', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='商品名稱',
               existing_nullable=False)
    op.alter_column('order_details', 'plu_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               comment=None,
               existing_comment='商品PluCode',
               existing_nullable=False)
    op.alter_column('order_details', 'id',
               existing_type=mysql.VARCHAR(length=28),
               comment=None,
               existing_comment='訂單編號',
               existing_nullable=False)
    op.drop_column('order_details', 'cherish_flg')
    op.drop_column('order_details', 'no_discount_type')
    op.alter_column('ifcontrls', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('ifcontrls', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_table('role_has_permissions')
    op.drop_index(op.f('ix_order_statuses_order_id'), table_name='order_statuses')
    op.drop_table('order_statuses')
    op.drop_table('model_has_roles')
    op.drop_table('model_has_permissions')
    op.drop_table('websockets_statistics_entries')
    op.drop_table('page_managers')
    op.drop_table('p_a_y_u_ni_diff_detail_files')
    op.drop_table('p_a_y_u_ni_diff_consolidate_files')
    op.drop_table('order_short_keys')
    op.drop_table('iftouchps')
    op.drop_table('ifpluexts')
    op.drop_table('ifnotdis')
    op.drop_table('ifmntexts')
    op.drop_table('ifbookms')
    op.drop_table('i_c_p_diff_detail_files')
    op.drop_table('i_c_p_diff_consolidate_files')
    op.drop_table('gps')
    op.drop_table('failed_jobs')
    op.drop_table('cathay_settle_detail_files')
    op.drop_table('cathay_settle_consolidate_files')
    op.drop_table('cathay_diff_detail_files')
    op.drop_table('cathay_diff_consolidate_files')
    op.drop_table('c_t_b_c_settle_detail_files')
    op.drop_table('c_t_b_c_settle_consolidate_files')
    op.drop_table('c_t_b_c_diff_detail_files')
    op.drop_table('c_t_b_c_diff_consolidate_files')
    op.drop_table('banks')
    op.drop_table('b_m_s_detail_files')
    op.drop_table('b_m_s_consolidate_files')
    # ### end Alembic commands ###
