"""migrate_stores_order_details_and_permissions

Revision ID: f865f7a8161a
Revises: ac9caa929345
Create Date: 2026-02-03 15:54:26.843425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f865f7a8161a'
down_revision: Union[str, Sequence[str], None] = 'ac9caa929345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ifcontrls',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('gm_id', sa.Text(), nullable=False),
    sa.Column('storeId', sa.String(length=6), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('long_name', sa.Text(), nullable=True),
    sa.Column('corp_name', sa.Text(), nullable=False),
    sa.Column('corp_name_2', sa.Text(), nullable=True),
    sa.Column('corp_id', sa.Text(), nullable=False),
    sa.Column('dis_flg', sa.Text(), nullable=False),
    sa.Column('dis_type', sa.Text(), nullable=False),
    sa.Column('discount', sa.Text(), nullable=False),
    sa.Column('dis_fra_flg', sa.Text(), nullable=False),
    sa.Column('ex_dis_flg', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_ifcontrls_storeId'), 'ifcontrls', ['storeId'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('guard_name', sa.String(length=125), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guard_name', name='uq_permission_name_guard')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('guard_name', sa.String(length=125), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guard_name', name='uq_role_name_guard')
    )
    op.create_table('stores',
    sa.Column('storeId', sa.String(length=6), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('gps', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('storeId')
    )
    op.create_index(op.f('ix_stores_storeId'), 'stores', ['storeId'], unique=False)
    op.create_table('order_details',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('plu_code', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('tax_flg', sa.String(length=2), nullable=False),
    sa.Column('is_discount', sa.Boolean(), nullable=False),
    sa.Column('discount_type', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('discount_fra_type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id', 'plu_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_index(op.f('ix_stores_storeId'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_ifcontrls_storeId'), table_name='ifcontrls')
    op.drop_table('ifcontrls')
    # ### end Alembic commands ###
